name: Deploy to AWS K3s

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Terraform Init & Apply
      uses: hashicorp/setup-terraform@v3
      with:
        tf_actions_version: latest
        tf_working_dir: ./terraform
        tf_init_options: -input=false
        tf_apply_options: -auto-approve

    - name: Get Terraform output
      id: tf_output
      run: echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/capstone-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/capstone-app:latest

    - name: Deploy to K3s via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ env.EC2_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo k3s kubectl apply -f ~/capstone-project/deployment.yaml
          sudo k3s kubectl apply -f ~/capstone-project/service.yaml
